
			<div id="content">
				<h1>Want to be a counselor? Here's what you need to know</h1>
				<hr>

					<h3>
					<strong>
					The Break for Jesus Organizing Committee is looking for some hard-working, fun-loving and creative teen counselors to assist in running this year’s programme.
					</strong>
					</h3>

				<br />
				<br />
				<h1>You should:</h1>
				<hr>
				<ul>
					<li>Be in grades 10 to 12 or older (grade 9 applicants will not be considered, no exceptions)</li>
					<li>Belong to a Ukrainian Catholic Parish</li>
					<li>Have several leadership qualities (hard working, mature, spiritual attitude, ability to work with children)</li>
					<li>Camp and/or catechism experience is an asset.</li>
					<li>Be available for March Break and counselor training (March 11 - 18, 2017)</li>
					<li>YOU MUST BE AVAILABLE for counselor training!</li>
				</ul>
				<h3>
				<strong>
					Interested applicants are asked to fill in an application form, found <a href="../resources/Counselor%20Form%202017.doc">here</a>. Email the filled out form to <a href="mailto:b4j@gmx.com">b4j@gmx.com</a> and <b>mail a hard copy</b> to the address provided in the form.
				</strong>
				</p>
				<br />
				<h1>The following information MUST be included:</h1>
				<hr>
				<ul>
					<li>Why do I want to be a counselor?</li>
					<li>Leadership experience (summer camps, retreats, catechism, youth group, previous B4J experience)</li>
					<li>What can you offer to make the children’s experience memorable?</li>
					<li>Level of Ukrainian: (none, minimal, medium or strong)</li>
					<li>Reference: (priest, nun, religion teacher, or youth worker who knows you)</li>
				</ul>
				<br />
				<h1>Note: Deadline Changed!</h1>
				<hr>
				<p>
					Applications must be submitted by <b>November 15, 2016</b>. (Please note earlier application deadline).
					You will be notified by <b>December 15, 2016</b> if you have been selected as a counselor.
					All personal information provided will be kept confidential
				</p>
				<br />
				<br />
				<h1>Application for police check:</h1>
				<hr>
				<h3>
				<strong>
					If you have not previously been a counselor at B4J and submitted a police check, please complete and send <a href="../resources/Criminal%20Offence%20Declaration%202017.doc">this</a> form along with your application.
				</strong>
				</h3>
				<p>
					After you have been selected to be a counselor you must apply for a police check.
					You will be reimbursed for the cost of obtaining the check.
					Apply in person at your local police station. Notify the police that this is a volunteer position. Allow 6-8 weeks for processing.
				</p>
			</div>
