			<div id="content">
				

				<h1>Donors 2013</h1>

				<br />
				<br />
				<h1>Major Sponsor $1000+</h1>
				<hr />
				
				<ul>
					<li>
						<h2 style="display:inline-block; font-weight:bold;">Ukrainian Credit Union</h2>
						<img style="display:inline-block; position:relative; top:10px; left:10px;" width="140px" height="45px" src="../images/ucu_logo.jpg"></img>
					</li>
				</ul>
				<br />
				<h1>Benefactors $500 - $750</h1>
				<hr />
				<ul>
                    <li><h2>Kantor Currency Exchange</h2></li>
                    <li><h2>The Great Martyr George the Victorious Ukr. Catholic Church (Oshawa)</h2></li>
                    <li><h2>UCWLC - St. Volodymyr Branch  (Thornhill Ontario)</h2></li>
                    <li><h2>UCWLC - Sts Peter & Paul Branch</h2></li>
                    <li><h2>UCWLC - Toronto Eparchial Executive</h2></li>
				</ul>
				<br />
				<h1>Donors up to $500</h1>
				<hr />
				<ul>
                    <li><h2>Buduchnist Credit Union</h2></li>
                    <li><h2>Dormition of the Mother of God Ukr. Catholic Church (Mississauga)</h2></li>
                    <li><h2>Holy Eucharist Ukr. Catholic Church</h2></li>
                    <li><h2>Holy Protection of the Mother of God Ukr. Catholic Church (Burlington)</h2></li>
                    <li><h2>Knights of Columbus Shashkevych Council 7464</h2></li>
                    <li><h2>Nativity of the Holy Mother of God Ukr. Catholic Church (Niagara Falls)</h2></li>
                    <li><h2>St. Demetrius the Great Martyr Ukr. Catholic Church (Toronto)</h2></li>
                    <li><h2>St. John the Theologian Ukr. Catholic Church (St. Catharines)</h2></li>
                    <li><h2>St. Mary's Ukr. Catholic Church (Sault St. Marie)</h2></li>
                    <li><h2>Sts Cyril & Methodius Ukr. Catholic Church (St. Catharines)</h2></li>
                    <li><h2>UCWLC - Dormition of the Mother of God Branch (Mississauga)</h2></li>
                    <li><h2>UCWLC - Holy Eucharist Branch</h2></li>
                    <li><h2>UCWLC - Holy Protection of Blessed Virgin Mary Branch (Burlington)</h2></li>
                    <li><h2>UCWLC - St. Demetrius Branch</h2></li>
                    <li><h2>UCWLC - St. Josaphat's Branch</h2></li>
                    <li><h2>UCWLC - St. Nicholas Branch</h2></li>
                    <li><h2>UCWLC - Sts Cyril & Methodius Branch</h2></li>
                    <li><h2>Ukr. Catholic Church of Holy Protection (Toronto)</h2></li>
                </ul>
			</div>
