		<div id="body">
			<div id="content">

				<h1>Donors 2017</h1>
				<a href="donors2016.html">(2016)</a>
				<br />
				<br />
				<br />
                <h1>$1000</h1>
                <hr />
                <ul>
                    <li><h2>Knights of Columbus, Sheptytsky council 5079, Toronto</h2></li>
                </ul>

                <br />

                <h1>$750</h1>
                <hr />
                <ul>
                    <li>
                        <h2 style="display:inline-block; font-weight:bold;">Ukrainian Credit Union</h2>
                        <img style="display:inline-block; position:relative; top:10px; left:10px;" width="140px" height="45px" src="../images/ucu_logo.jpg"></img>
                    </li>
                </ul>

                <br />

				<h1>$500</h1>
				<hr />
				<ul>
					<li><h2>Knights of  Columbus,  Shashkevych Council  7464, Hamilton</h2></li>
					<li><h2>St. Demetrius the Great Martyr Ukrainian Catholic Church  (Toronto)</h2></li>
					<li><h2>Sts. Cyril & Methodius Ukrainian Catholic Church (St. Catharines)</h2></li>
					<li><h2>The Great Martyr George the Victorious Ukrainian Catholic Church (Oshawa)</h2></li>
                    <li><h2>The Order of St. Basil the Great in Canada (Ottawa)</h2></li>
                    <li><h2>UCWLC, St. Nicholas Branch (Toronto)</h2></li>
                    <li><h2>UCWLC Sts Peter and Paul Branch (Scarborough)</h2></li>
                </ul>

                <br />

                <h1>$300</h1>
				<hr />
                <ul>
                    <li><h2>Holy Eucharist Ukrainian Catholic Church (Toronto)</h2></li>
                    <li><h2>Holy Protection of the Mother of God Ukrainian Catholic Church (Guelph)</h2></li>
                    <li><h2>Holy Protection of the Mother of God Ukrainian Catholic Church (Sudbury)</h2></li>
                    <li><h2>Nativity of the Mother of God Ukrainian Catholic Church (Sault Ste. Marie)</h2></li>
                    <li><h2>St. Joseph's Ukrainian Catholic Church (Oakville)</h2></li>
                    <li><h2>UCWLC, St. Demetrius Branch (Toronto)</h2></li>
                    <li><h2>UCWLC, Sts. Cyril & Methodius Branch (St. Catharines)</h2></li>
                    <li><h2>UCWLC, Dormition of Mother of God Branch (Mississauga)</h2></li>
                </ul>

                <br />

                <h1>$250</h1>
				<hr />
                <ul>
                    <li><h2>Church Of The Holy Protection Ukrainian Catholic Church  (Toronto)</h2></li>
                    <li><h2>Holy Spirit Ukrainian Catholic Church (Hamilton)</h2></li>
                    <li><h2>Holy Spirit Ukrainian Catholic Church -perogies (Hamilton)</h2></li>
                    <li><h2>Nativity of the Mother of God Ukrainian Catholic Church (Niagara Falls)</h2></li>
                    <li><h2>St. Elias the Prophet Ukrainian Catholic Church (Brampton)</h2></li>
                    <li><h2>St. John the Theologian Ukrainian Catholic Church (St. Catharines)</h2></li>
                    <li><h2>UCWLC, Holy Protection of the MOther of God Branch (Burlington)</h2></li>
                    <li><h2>UCWLC, Holy Transfiguration Branch (Kitchener)</h2></li>
                    <li><h2>UCWLC, St. Josaphat's Cathedral Branch (Toronto)</h2></li>
                    <li><h2>Ukrainian Catholic Church of the Transfiguration (Kitchener)</h2></li>
                </ul>

                <br />

                <h1>$150</h1>
                <hr />
                <ul>
                    <li><h2>John Romaniuk, Cross vendor, CNC Woodcraft, (St. Catharines)</h2></li>
                </ul>

                <h1>$100</h1>
                <hr />
                <ul>
                    <li><h2>St. Michael the Archangel Ukrainian Catholic Church (Welland)</h2></li>
                    <li><h2>UCWLC St. Volodymyr Branch (Newmarket)</h2></li>
                </ul>

				<p>We welcome new donations to cover our costs. Please make out cheques to <b>"Break For Jesus"</b> and mail to: </p>
				<p>6 Upminster Cres., Toronto ON, M9B 5W2</p>
				<p>If you would like a tax receipt, please make cheque out to <b>"Sts. Cyril & Methodius Church - Break For Jesus"</b> and mail to: </p>
				<p>14 Rolls Ave, St. Catharines ON, L2N 1W1</p>

				<br />
				<br />
				<br />
				<br />
			</div>
