			<div id="content">


				<h1>Donors 2015</h1>
				<a href="donors2014.phtml">(2014)</a>
				<br />

				<br />
				<br />
				<h1>$1000</h1>
				<hr />
				<ul>
                    <li><h2>Anonymous</h2></li>
				</ul>
				<br />

				<h1>$750</h1>
				<hr />
				<ul>
                    <li>
						<h2 style="display:inline-block; font-weight:bold;">Ukrainian Credit Union</h2>
						<img style="display:inline-block; position:relative; top:10px; left:10px;" width="140px" height="45px" src="../images/ucu_logo.jpg"></img>
					</li>
                    <li><h2>UCWLC - Sts. Peter and Paul Branch, Scarborough</h2></li>
                </ul>

                <br />

				<h1>$500</h1>
				<hr />
				<ul>
					<li><h2>Buduchnist Credit Union</h2></li>
					<li><h2>St. George the Great Martyr Church, Oshawa</h2></li>
					<li><h2>St. Nicholas Church, Toronto</h2></li>
					<li><h2>UCWLC St. Nicholas Branch, Toronto</h2></li>
                </ul>

                <br />

                <h1>$300 - $400</h1>
				<hr />
                <ul>
                    <li><h2>Dormition of the Mother of God Church, Mississauga</h2></li>
                    <li><h2>Holy Protection Church, Guelph</h2></li>
                    <li><h2>Knights of Columbus Shashkevych Council 7464, Grimsby</h2></li>
                    <li><h2>Nativity of the Mother of God Church, Sault Ste Marie</h2></li>
                    <li><h2>Sts. Cyril and Methodius Church, St. Catharines</h2></li>
                    <li><h2>St. Demetrius Church, Toronto</h2></li>
                    <li><h2>UCWLC St. Demetrius Branch, Toronto</h2></li>
                </ul>

                <br />

                <h1>$100 - $250</h1>
				<hr />
                <ul>
                    <li><h2>Exhaltation of the Holy Cross Church, Thunder Bay</h2></li>
                    <li><h2>Holy Spirit Church, Hamilton</h2></li>
                    <li><h2>Holy Spirit (Perogies), Hamilton</h2></li>
                    <li><h2>Holy Transfiguration Church, Kitchener</h2></li>
                    <li><h2>Nativity of the Mother of God Church, Niagara Falls</h2></li>
                    <li><h2>Steve Gaida (Aristocrat Flooring), St. Catharines</h2></li>
                    <li><h2>St. Michaels Church, Welland</h2></li>
                    <li><h2>UCWLC Dormition of the Mother of God Branch, Mississauga</h2></li>
                    <li><h2>UCWLC Holy Protection Branch, Burlington</h2></li>
                    <li><h2>UCWLC Holy Transfiguration Branch, Kitchener</h2></li>
                    <li><h2>UCWLC Sts. Cyril and Methodius Branch, St. Catharines</h2></li>
                    <li><h2>UCWLC St. Josaphat Branch, Toronto</h2></li>
                </ul>

                <br />

                <h1>Up to $100</h1>
				<hr />
                <ul>
                    <li><h2>Rev. Mitchell Kita, Burlington</h2></li>
                    <li><h2>St. John's Church, Brantford</h2></li>
                    <li><h2>UCWLC St. John's Branch, Brantford</h2></li>
                </ul>

				<p>We welcome new donations to cover our costs. Please make out cheques to <b>"Break For Jesus"</b> and mail to: </p>
				<p>6 Upminster Cres., Toronto ON, M9B 5W2</p>
				<p>If you would like a tax receipt, please make cheque out to <b>"Sts. Cyril & Methodius Church - Break For Jesus"</b> and mail to: </p>
				<p>14 Rolls Ave, St. Catharines ON, L2N 1W1</p>

				<br />
				<br />
				<br />
				<br />
			</div>
