		<div id="body">
			<div id="content">


				<h1>Donors 2016</h1>
				<a href="donors2015.html">(2015)</a>
				<br />
				<br />
				<br />

				<h1>$750</h1>
				<hr />
				<ul>
                    <li><h2>UCWLC - Sts. Peter and Paul Branch, Scarborough</h2></li>
                </ul>

                <br />

                <h1>$600</h1>
				<hr />
				<ul>
                    <li>
						<h2 style="display:inline-block; font-weight:bold;">Ukrainian Credit Union</h2>
						<img style="display:inline-block; position:relative; top:10px; left:10px;" width="140px" height="45px" src="../images/ucu_logo.jpg"></img>
					</li>
                </ul>

                <br />

				<h1>$500</h1>
				<hr />
				<ul>
					<li><h2>Holy Eucharist Ukr. Cath. Church, Toronto</h2></li>
					<li><h2>Sts Cyril and Methodius Ukr. Cath. Church, St Catharines</h2></li>
					<li><h2>St John the Baptist Ukr. Cath. Shrine, Ottawa</h2></li>
					<li><h2>St Nicholas Ukr. Cath. Church, Toronto</h2></li>
                </ul>

                <br />

                <h1>$300 - $400</h1>
				<hr />
                <ul>
                    <li><h2>Holy Protection of the Mother of God Ukr. Cath. Church, Sudbury</h2></li>
                    <li><h2>Knight of Columbus, Shashkevych Council, Hamilton</h2></li>
                    <li><h2>Nativity of the Mother of God Ukr. Cath. Church, Sault Ste Marie</h2></li>
                    <li><h2>Nativity of the Mother of God Ukr. Cath. Church, Niagara Falls</h2></li>
                    <li><h2>St Demetrius  Ukr. Cath. Church, La Rose, Toronto</h2></li>
                    <li><h2>UCWLC Eparchy of Toronto, Eparchial Executive</h2></li>
                    <li><h2>UCWLC St Demetrius branch, (La Rose), Toronto</h2></li>
                    <li><h2>UCWLC Sts Cyril and Methodius branch, St. Catharines</h2></li>
                    <li><h2>Ukrainian Canadian Congress, Niagara Region branch</h2></li>
                </ul>

                <br />


                <h1>$100 - $250</h1>
				<hr />
                <ul>
                    <li><h2>Buduchnist Credit Union</h2></li>
                    <li><h2>Deacon David Kennedy</h2></li>
                    <li><h2>Deacon Mike Melnyk</h2></li>
                    <li><h2>Dormition of the Mother of God Ukr. Cath. Church, Mississauga</h2></li>
                    <li><h2>Fr. Roman and Dobr. Iryna Galadza</h2></li>
                    <li><h2>Holy Protection of the Mother of God Ukr. Cath. Church, (Leeds) Toronto</h2></li>
                    <li><h2>Holy Protection of the Mother of God Ukr. Cath. Church, Burlington</h2></li>
                    <li><h2>Holy Spirit Ukr. Cath. Church (Perogies), Hamilton</h2></li>
                    <li><h2>Holy Spirit Ukr. Cath. Church, Hamilton</h2></li>
                    <li><h2>St John the Theologian, Ukr. Cath. Church, St. Catharines</h2></li>
                    <li><h2>St Michael the Archangel Ukr. Cath. Church, Welland</h2></li>
                    <li><h2>St. Elias the Prophet Ukr. Cath. Church, Brampton</h2></li>
                    <li><h2>UCWLC Holy Protection branch, Burlington</h2></li>
                    <li><h2>UCWLC Holy Protection branch, Leeds Toronto</h2></li>
                    <li><h2>UCWLC Holy Transfiguration branch, Kitchener</h2></li>
                    <li><h2>UCWLC St George the Great Martyr branch, Oshawa</h2></li>
                    <li><h2>UCWLC St. Josaphat branch, Toronto</h2></li>
                    <li><h2>Ukr. Cath. Church of the Transfiguration, Kitchener</h2></li>
                </ul>

				<p>We welcome new donations to cover our costs. Please make out cheques to <b>"Break For Jesus"</b> and mail to: </p>
				<p>6 Upminster Cres., Toronto ON, M9B 5W2</p>
				<p>If you would like a tax receipt, please make cheque out to <b>"Sts. Cyril & Methodius Church - Break For Jesus"</b> and mail to: </p>
				<p>14 Rolls Ave, St. Catharines ON, L2N 1W1</p>

				<br />
				<br />
				<br />
				<br />
			</div>
