			<div id="content">


				<h1>Donors 2014</h1>
				<a href="donors2013.phtml">(2013)</a>
				<br />

				<br />
				<br />
				<h1>$750</h1>
				<hr />
				
				<ul>
					<li>
						<h2 style="display:inline-block; font-weight:bold;">Ukrainian Credit Union</h2>
						<img style="display:inline-block; position:relative; top:10px; left:10px;" width="140px" height="45px" src="../images/ucu_logo.jpg"></img>
					</li>
				</ul>
				<br />

				<h1>$500 - $700</h1>
				<hr />
				<ul>
                    <li><h2>St. Demetrius Church, Toronto</h2></li>
                    <li><h2>St. George the Great Martyr, Oshawa</h2></li>
                    <li><h2>UCWLC, St. Nicholas Church, Toronto</h2></li>
				</ul>
				<br />

				<h1>$300 - $500</h1>
				<hr />
				<ul>
                    <li><h2>Church of the Holy Spirit, (perogies committee), Hamilton</h2></li>
                    <li><h2>Church of the Holy Spirit, Hamilton</h2></li>
                    <li><h2>Fr. John Tataryn</h2></li>
                    <li><h2>Nativity of the Holy Mother of God Church, Niagara Falls</h2></li>
                    <li><h2>St. Mary’s Church, Sault Saint Marie</h2></li>
                    <li><h2>Sts. Cyril and Methodius Church, St. Catharines</h2></li>
                    <li><h2>UCWLC, St. Demetrius Church, Toronto</h2></li>
                </ul>

                <br />

				<h1>$100 - $300</h1>
				<hr />
				<ul>
					<li><h2>St. Josaphat's Cathedral, Toronto</h2></li>
                    <li><h2>Knight of Columbus Sheptycky Council #7464, Grimsby</h2></li>
                    <li><h2>St. Mary’s Church, Sudbury</h2></li>
                    <li><h2>St. Mary’s Dormition Church, Mississauga</h2></li>
                    <li><h2>UCWLC, Protection on the Holy Mother of God Church, Burlington</h2></li>
                    <li><h2>UCWLC, Sts. Cyril and Methodius Church, St. Catharines</h2></li>
                    <li><h2>UCWLC, Toronto Eparchial Executive</h2></li>
                </ul>

                <br />

                <h1>Up To $100</h1>
				<hr />
                <ul>
                    <li><h2>Nadiya Stasyna, Toronto</h2></li>
                    <li><h2>St. John the Baptist Church, Brantford</h2></li>
                    <li><h2>UCWLC, St. John the Baptist Church, Brantford</h2></li>
                </ul>

				<p>We welcome new donations to cover our costs. Please make out cheques to <b>"Break For Jesus"</b> and mail to: </p>
				<p>6 Upminster Cres., Toronto ON, M9B 5W2</p>
				<p>If you would like a tax receipt, please make cheque out to <b>"Sts. Cyril & Methodius Church - Break For Jesus"</b> and mail to: </p>
				<p>14 Rolls Ave, St. Catharines ON, L2N 1W1</p>

				<br />
				<br />
				<br />
				<br />
			</div>
