		<div id="body">
			<div id="content">

				<h1>Donors 2018</h1>
				<a href="donors2017.html">(2017)</a>
				<br />
				<br />
				<br />

				<h1>$2,500</h1>
				<hr />
				<ul>
                    <li><h2>Ukrainian Catholic Episcopal Corporation</h2></li>
                </ul>

                <br />

				<h1>$2,000</h1>
				<hr />
				<ul>
                    <li><h2>K of C Sheptytsky council 5079 (Toronto)</h2></li>
                    <li><h2>Anonymous</h2></li>
                </ul>

                <br />

                <h1>$1,000</h1>
                <hr />
                <ul>
                    <li>
                        <h2 style="display:inline-block; font-weight:bold;">Ukrainian Credit Union</h2>
                        <img style="display:inline-block; position:relative; top:10px; left:10px;" width="140px" height="45px" src="../images/ucu_logo.jpg"></img>
                    </li>
                </ul>

                <br />

				<h1>$500</h1>
				<hr />
				<ul>
					<li><h2>St. Demetrius the Great Martyr Ukrainian Catholic Church (La Rose, Toronto)</h2></li>
					<li><h2>Sts. Cyril & Methodius Ukrainian Catholic Church (St. Catharines)</h2></li>
					<li><h2>St. John the Baptist Ukr. Catholic Shrine (Ottawa)</h2></li>
					<li><h2>K of C Shashkevych Council  7464 (Hamilton)</h2></li>
					<li><h2>UCWLC (St. Nicholas Branch, Bellwoods)</h2></li>
					<li><h2>UCWLC Sts Peter and Paul Branch (Scarborough)</h2></li>
                </ul>

                <br />

                <h1>$400</h1>
				<hr />
				<ul>
                    <li><h2>Holy Protection of the Mother of God Ukrainian Catholic Church (Burlington)</h2></li>
                </ul>

                <br />

                <h1>$350</h1>
				<hr />
                <ul>
                    <li><h2>Holy Eucharist Ukrainian Catholic Church (Broadview, Toronto)</h2></li>
                    <li><h2>UCWLC Eparchy of Toronto</h2></li>
                </ul>

                <br />

                <h1>$300</h1>
				<hr />
                <ul>
                    <li><h2>Nativity of the Mother of God Ukrainian Catholic Church (Niagara Falls)</h2></li>
                    <li><h2>Nativity of the Mother of God Ukrainian Catholic Church (Sault Ste. Marie)</h2></li>
                    <li><h2>St. Joseph's Ukrainian Catholic Church (Oakville)</h2></li>
                    <li><h2>Holy Protection of the Mother of God Ukrainian Catholic Church (Guelph)</h2></li>
                    <li><h2>Ukrainian Catholic Church of the Transfiguration (Kitchener)</h2></li>
                    <li><h2>UCWLC (Sts. Cyril & Methodius Branch, St. Catharines)</h2></li>
                </ul>

                <br />

                <h1>$250</h1>
				<hr />
                <ul>
                    <li><h2>Holy Protection of the Mother of God Ukrainian Catholic Church (Sudbury)</h2></li>
                </ul>

                <br />

                <h1>$200</h1>
                <hr />
                <ul>
                    <li><h2>St. John the Theologian Ukrainian Catholic Church (St. Catharines)</h2></li>
                    <li><h2>St. Michael the Archangel Ukrainian Catholic Church (Welland)</h2></li>
                    <li><h2>UCWLC Holy Protection Branch (Burlington)</h2></li>
                    <li><h2>UCWLC Holy Transfiguration Branch (Kitchener)</h2></li>
                    <li><h2>Holy Spirit Ukrainian Catholic Church (Hamilton)</h2></li>
                    <li><h2>Holy Spirit Ukrainian Catholic Church -perogies (Hamilton)</h2></li>
                </ul>

                <br />

                <h1>$100</h1>
                <hr />
                <ul>
                    <li><h2>The Great Martyr George the Victorious Ukrainian Catholic Church (Oshawa)</h2></li>
                    <li><h2>St. Elias the Prophet Church (Brampton)</h2></li>
                </ul>

				<p>We welcome new donations to cover our costs. Please make out cheques to <b>"Break For Jesus"</b> and mail to: </p>
				<p>6 Upminster Cres., Toronto ON, M9B 5W2</p>
				<p>If you would like a tax receipt, please make cheque out to <b>"Sts. Cyril & Methodius Church - Break For Jesus"</b> and mail to: </p>
				<p>14 Rolls Ave, St. Catharines ON, L2N 1W1</p>

				<br />
				<br />
				<br />
				<br />
			</div>
