<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>B4J - Contact</title>
    <link rel="stylesheet" type="text/css" href="../css/style.css">
</head>
<body>
<div id="page">
    <div id="header">
        <a href="index.html" id="logo"><img src="../images/logo.png" alt="Logo"></a>
        <ul>
            <li>
                <a href="index.html">Home</a>
            </li>
            <li>
                <a href="poster.html">Poster</a>
            </li>
            <li>
                <a href="photos.html">Photos</a>
            </li>
            <li>
                <a href="donors.html">Donors</a>
            </li>
            <li>
                <a href="counselors.html">Counselors</a>
            </li>
            <li class="current">
                <a href="contact.html">Contact</a>
            </li>
        </ul>
    </div>
    <div id="body">