			<div class="header">
				<div>
					<a href="index.html"><img src="../images/chapel.jpg" alt="Image"></a>
					<div>
						<h1>What is B4J ?</h1>
						<p>
							With the blessing of our bishop, we offer a week long camp celebrating our faith in a fun and friendly environment.
							<br />
							For Ukrainian Catholic children of the Eparchy of Toronto in grades 3 - 8. Program conducted in both Ukrainian and English.
						</p>
					</div>
				</div>
				<ul>
					<li>
						<span class="figure"><img src="../images/thumb1.png" alt="Image"></span>
						<h3><span>When</span></h3>
						<p>Sun March 12th (5pm) to Sat March 18th (10 am) 2017.</p>

					</li>
					<li>
						<span class="figure"><img src="../images/thumb2.png" alt="Image"></span>
						<h3><span>Where</span></h3>

						<p>Mount Mary Retreat Centre in Ancaster
						<a href="https://maps.google.ca/maps?f=q&source=s_q&hl=en&geocode=&q=Mount+Mary+Retreat+Centre&aq=&sll=43.272523,-79.482372&sspn=0.604935,1.234589&vpsrc=0&t=h&ie=UTF8&hq=Mount+Mary+Retreat+Centre&hnear=&ll=43.272206,-79.573975&spn=0.604935,1.234589&z=10&iwloc=A&cid=1011592080270717859">map</a>
						</p>
						
					</li>
					<li class="last">
						<span class="figure"><img src="../images/thumb3.png" alt="Image"></span>
						<h3><span>Register</span></h3>
						<p><a href="registration.html">click here for more info</a></p>
						
					</li>
				</ul>
			</div>

