			<div id="content">
				<h1>Photos 2013</h1>
				<ul class="section">
					<li>
						<h2>Group Photos</h2>
						<embed type="application/x-shockwave-flash" src="https://static.googleusercontent.com/external_content/picasaweb.googleusercontent.com/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F5868341867187685377%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCKrF4JaZuuW8RQ%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Chapel</h2>
						<embed type="application/x-shockwave-flash" src="https://static.googleusercontent.com/external_content/picasaweb.googleusercontent.com/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F5867256454055955585%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCL2vgPXeqvznAQ%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Spiv</h2>
						<embed type="application/x-shockwave-flash" src="https://static.googleusercontent.com/external_content/picasaweb.googleusercontent.com/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F5867248046557909473%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCLLLkpi07u6URg%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Outside</h2>
						<embed type="application/x-shockwave-flash" src="https://static.googleusercontent.com/external_content/picasaweb.googleusercontent.com/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F5867249520900896209%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCKya-_rp6szXCA%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Bingo</h2>
						<embed type="application/x-shockwave-flash" src="https://static.googleusercontent.com/external_content/picasaweb.googleusercontent.com/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F5867251242066835777%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCOmqg4a9qoS0UA%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Caf Activities</h2>
						<embed type="application/x-shockwave-flash" src="https://static.googleusercontent.com/external_content/picasaweb.googleusercontent.com/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F5867251507611854913%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCObkyrC26t-2_AE%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Olympiada</h2>
						<embed type="application/x-shockwave-flash" src="https://static.googleusercontent.com/external_content/picasaweb.googleusercontent.com/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F5867251865301302065%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCKrPg72kyt_A7AE%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Crafts</h2>
						<embed type="application/x-shockwave-flash" src="https://static.googleusercontent.com/external_content/picasaweb.googleusercontent.com/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F5867255359293059249%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCPCSuq-T877vKg%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Bowling</h2>
						<embed type="application/x-shockwave-flash" src="https://static.googleusercontent.com/external_content/picasaweb.googleusercontent.com/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F5867250719258583057%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCKTMr8-Ito3_FA%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Swimming</h2>
						<embed type="application/x-shockwave-flash" src="https://static.googleusercontent.com/external_content/picasaweb.googleusercontent.com/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F5867250045732810401%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCJ3Y75PEzYLRjAE%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Prayer Walk</h2>
						<embed type="application/x-shockwave-flash" src="https://static.googleusercontent.com/external_content/picasaweb.googleusercontent.com/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F5867247869167489777%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCOa_s6jngovgNQ%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>						
					</li>
					<li>
						<h2>Sports</h2>
						<embed type="application/x-shockwave-flash" src="https://static.googleusercontent.com/external_content/picasaweb.googleusercontent.com/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F5867254242149094913%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCJzx77rp6MfucA%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>						
					</li>
					<li>
						<h2>Day Group Activities</h2>
						<embed type="application/x-shockwave-flash" src="https://static.googleusercontent.com/external_content/picasaweb.googleusercontent.com/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F5867257790129302769%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCMPr_K6mws7zJQ%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Dorms</h2>
						<embed type="application/x-shockwave-flash" src="https://static.googleusercontent.com/external_content/picasaweb.googleusercontent.com/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F5867255933264113793%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCMCf-ebHo-ivtAE%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Caf</h2>
                        <embed type="application/x-shockwave-flash" src="https://static.googleusercontent.com/external_content/picasaweb.googleusercontent.com/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F5867251507611854913%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCObkyrC26t-2_AE%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Skits</h2>
						<embed type="application/x-shockwave-flash" src="https://static.googleusercontent.com/external_content/picasaweb.googleusercontent.com/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F5867257357469551201%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCN6zjOzs3uCRLg%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
				</ul>
			</div>
