			<div id="content">
				<h1>Photos 2016</h1>
				<a href="photos_2015.html">(last year's photos)</a>
				<ul class="section">

					<li>
						<h2>Group Photos <a href="https://goo.gl/photos/YXcfLshcM1WScLQC9">link</a></h2> 
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&hnoautoplay=1&l=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6266033648062765905%3Falt%3Drss%26kind%3Dphoto%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>

					<li>
						<h2>Counselors <a href="https://goo.gl/photos/srS28G5efajt8vzd8">link</a></h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6266035028969267761%3Falt%3Drss%26kind%3Dphoto%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>

					<li>
						<h2>Chapel <a href="https://goo.gl/photos/zCUaC55Wje4oENir8">link</a></h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6266041025335182065%3Falt%3Drss%26kind%3Dphoto%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>


					<li>
						<h2>Bingo <a href="https://goo.gl/photos/dPcnj9zX7kqe8Mmt8">link</a></h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6266061277768358545%3Falt%3Drss%26kind%3Dphoto%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>

					<li>
						<h2>Olympiada <a href="https://goo.gl/photos/Kgh9WN8Mq5x5FYku9">link</a></h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6266076616778453345%3Falt%3Drss%26kind%3Dphoto%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					
					<li>
						<h2>Craft <a href="https://goo.gl/photos/Dra5fiMqNFeBmdHk6">link</a></h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6266121385059927345%3Falt%3Drss%26kind%3Dphoto%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>

					<li>
						<h2>Spiv <a href="https://goo.gl/photos/4s5Uei7PvQBbjGMt9">link</a></h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6266145297428570737%3Falt%3Drss%26kind%3Dphoto%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>


					<li>
						<h2>Skits <a href="https://goo.gl/photos/UGWvmw2UXRq3UaFx7">link</a></h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6266204478024168769%3Falt%3Drss%26kind%3Dphoto%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>


					<li>
						<h2>Mealtime <a href="https://goo.gl/photos/uhzmtM713X8GmXT17">link</a></h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6266160680686066433%3Falt%3Drss%26kind%3Dphoto%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>

					<li>
						<h2>Praying in Colour <a href="https://goo.gl/photos/P6fRCzqCmUxzAZKXA">link</a></h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6266368323302813009%3Falt%3Drss%26kind%3Dphoto%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>

					<li>
						<h2>Outside Break <a href="https://goo.gl/photos/3QvFREoA1X6pAYsV8">link</a></h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6266376349092989969%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCJvVqpWi0N-62wE%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>

					<li>
						<h2>Vatra <a href="https://goo.gl/photos/p2agvAmjcRf27pWA9">link</a></h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6266108115536866145%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCPfd4OG4jI35Wg%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>

					<li>
						<h2>Prayer Walk for Ukraine <a href="https://goo.gl/photos/DuzLz1FNKRYg8HSVA">link</a></h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6266104871831060929%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCJDHqu3an9KeMA%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>

					<li>
						<h2>Free Style Soccer <a href="https://goo.gl/photos/4aXNwMb6uhzEX2vJ7">link</a></h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6266099173893416897%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCIvDp97vgcn_GA%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>

					<li>
						<h2>Trampoline Park <a href="https://goo.gl/photos/AdZcYheFvGJ2ixSRA">link</a></h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6266090818611905025%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCNvkr6b-z7CL7QE%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>

					<li>
						<h2>Sports <a href="https://goo.gl/photos/DohUTQYPzRmEeHds5">link</a></h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6266114903343690913%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCOzetpmBqIm3GA%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>

					<li>
						<h2>Dorms <a href="https://goo.gl/photos/3XAMbWwX7Uj7R3es6">link</a></h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6266151503543462753%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCK7et83Gv6vWlQE%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>

					<li>
						<h2>Nauka <a href="https://goo.gl/photos/h4JwovCXPU7XAXkn6">link</a></h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="533" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6266214892717441729%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCKzLotXYnKOnwgE%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
				</ul>
			</div>
