			<!-- 3. Enjoy! -->
			<div id="content">
				<h1>Photos 2017</h1>
				<a href="photos_2016.html">(last year's photos)</a>
				<ul class="section2">

					<li>
						<h2>Group Photos</h2>
						<div style="margin: 0 auto; width: 100%; height: 627px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/1piBEgoWAKq6pw92PmMPfsTqURpemilcSg9fIkJTr_q8/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="627" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Councelors</h2>
						<div style="margin: 0 auto; width: 100%; height: 627px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/11eH7CXjlzHS06T82OAV8TtKxOe_HaSrfC2TZs9rhjwU/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="627" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Staff</h2>
						<div style="margin: 0 auto; width: 100%; height: 627px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/1cm4sZRAL8I6lIWHZdrLC_NXwoIB7mAIZWuOaRQIjKBo/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="627" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Chapel</h2>
						<div style="margin: 0 auto; width: 100%; height: 480px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/18TO53qZxnyV6tuBUo2KDdPA2j0lgUEeyzgwRpUTpZNQ/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="480" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Bingo</h2>
						<div style="margin: 0 auto; width: 100%; height: 480px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/1gBY-4Gk5XqdI4Vwbo0o62eAmvOfQgH08Q4Z7XPq1HyM/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="480" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Olympiada</h2>
						<div style="margin: 0 auto; width: 100%; height: 480px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/1r0pC-cYtUE_fh4guxi8qTXiiSnEreaHKcagdT0ONHfw/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="480" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Craft</h2>
						<div style="margin: 0 auto; width: 100%; height: 480px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/1nj4cbmaWM50eBW4PPrraMpeOpfOO28nLyAv5AtAN8NY/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="480" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Nauka</h2>
						<div style="margin: 0 auto; width: 100%; height: 480px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/11xuCSqSYxoI5XEPJV6n3BC_rZbmgqnOXH48KQYf7YZQ/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="480" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Outside</h2>
						<div style="margin: 0 auto; width: 100%; height: 480px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/1EcW0yyHWuDM9tMr748cUJaJFTVRLG021WI2uoAXZz0c/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="480" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Food</h2>
						<div style="margin: 0 auto; width: 100%; height: 480px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/19RMLQW1-sBAHsp2xL-V3MxnCSifi-0RaCVqeQHODLkQ/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="480" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Trip</h2>
						<div style="margin: 0 auto; width: 100%; height: 480px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/12C7EFlZ4gvuB0gTDNT-tCKTZnTgo8j3YOFjEbqYxXeI/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="480" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Spiv</h2>
						<div style="margin: 0 auto; width: 100%; height: 480px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/1inb_2N9o4tC6hLzJLk-qq9FMVeQdurOXa5sAB6GI5ng/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="480" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Sport</h2>
						<div style="margin: 0 auto; width: 100%; height: 480px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/1hCBQLxVe3SX1mf4ldGUti7SfWZNOT1ZulqDX7lGDCC0/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="480" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Skits</h2>
						<div style="margin: 0 auto; width: 100%; height: 480px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/1etYVWatBp0MfO_Cvu1r5lR85Mz26_d7Af9BW14z7e2Q/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="480" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Prayer Walk and Vatra</h2>
						<div style="margin: 0 auto; width: 100%; height: 480px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/1Wy3o9-dgVbyEBi8a0hNXpzUnIwv43nSI91SfIoOJWFw/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="480" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Dorms</h2>
						<div style="margin: 0 auto; width: 100%; height: 480px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/1zlEC2IZfBm8WJJxxf91CAYo1AdEmJ8XWVtr2pDoxkDU/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="480" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
				</ul>
			</div>
