			<div id="content">
				<h1>Photos 2015</h1>
				<a href="photos_2014.html">(last year's photos)</a>
				<ul class="section">

					<li>
						<h2>Group Photos</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6146683032973176113%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCNbMlPmUpZTylAE%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>

					<li>
						<h2>Counselors</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6146923996067297393%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCLup0aGl877JaQ%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>

					<li>
						<h2>Our Staff</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6147065188886783457%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCO6u49KR5eWisgE%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>

					<li>
						<h2>Chapel</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6146915110511020545%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCP6c4NbogfDg2AE%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>

					<li>
						<h2>Visit with Soldier</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6147298187591940321%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCITa3uWslbKFWw%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>

					<li>
						<h2>Bingo</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6146629746209056689%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCMfq9Z6X_MHOAQ%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed> 
					</li>

					<li>
						<h2>Olympiada</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960	" height="553" flashvars="host=picasaweb.google.com&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6147063168604538513%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCP7l-PWeiNHFMg%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>

					<li>
					    <h2>Bowling</h2>
					    <embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6146917297630223825%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCOLihrfvvIfOOA%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>

					<li>
						<h2>Swimming</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6147298156642101601%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCK_thfvyyMC_NQ%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>

					<li>
						<h2>Prayer walk for Ukraine</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6147227887234840977%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCJfbt4D9xY6yhQE%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>

					<li>
						<h2>Sports</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6147241540855504161%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCKLwory-9uCe1QE%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>

					<li>
						<h2>Crafts</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6146930848813614625%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCLfT_NrU7s7tSw%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>

					<li>
						<h2>Spiv</h2>
					    <embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6147241373493769697%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCPzDy7fGgcLiMg%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>	

					<li>
						<h2>Dorms</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6146959731793111761%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCPvV5uawkIaRKw%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>	

					<li>
						<h2>Meal time</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6147065867757831793%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCIOZvJ6_9tODmQE%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>

					<li>
						<h2>Skits</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6147241205493059681%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCJ-viIrqpdO2ngE%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>

					<li>
						<h2>Outside break</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6147227848357225489%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCKCQkurp26vnvAE%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>

					<li>
						<h2>Nauka</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6147061538898971489%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCPWrs9reg_L20gE%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					
					<li>
						<h2>Closing of Camp</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6146920430825784337%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCIqdzKLO1P6UCw%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					
				</ul>
			</div>
