			<div id="content">
				<h1>Photos 2014</h1>
				<a href="photos_2013.html">(last year's photos)</a>
				<ul class="section">
					<li>
						<h2>Group Photos</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6000082797291138337%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCJ2qmdutobO-xgE%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Chapel, Bishop's Visit, Prayer Walk</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6000073116588348657%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCMO1lYHF-LbFLA%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Skits</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6000070257459664321%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCKGoiunB97LuhgE%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Swimming</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6000070562386226961%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCIOGvcH1_5zJ9QE%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Reptile Man</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6000071668015467025%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCP6w-u-6-JOGeA%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Olympiada</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6000075911551730545%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCMXS-e_96craeQ%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Dorms</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6000079156915264193%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCMmR8a3DyLWPTA%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Outdoors</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6000079394503557633%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCKDxodib7IuTAw%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Meal Time</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6000080482156042561%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCNeQy4urmJWw4AE%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Bingo & Prizes</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6000081020710123393%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCOua7rKP_LnCxAE%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Spiv</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6000082321542522529%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCIPq7bKj3ZqEHQ%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Sports</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6000083133830938833%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCK3S7vTRp6DsUQ%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Arts & Crafts</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6000084834750918577%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCL6d64yZxruVGQ%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Nauka</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6000085413655616385%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCJzT6vjesbL7nAE%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Ice Breakers</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6000085959203088145%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCPeYy-K3rdm6lQE%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Counselors</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6000087264206833953%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCPKDjvzIjJzRjwE%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
					<li>
						<h2>Nurse Anna / Miscellaneous</h2>
						<embed type="application/x-shockwave-flash" src="https://photos.gstatic.com/media/slideshow.swf" width="960" height="553" flashvars="host=picasaweb.google.com&noautoplay=1&hl=en_US&feat=flashalbum&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F111584921390391498934%2Falbumid%2F6000074649365322497%3Falt%3Drss%26kind%3Dphoto%26authkey%3DGv1sRgCM22zeTsv9-0LA%26hl%3Den_US" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
					</li>
				</ul>
			</div>
