			<!-- 3. Enjoy! -->
			<div id="content">
				<h1>Photos 2018</h1>
				<a href="photos_2017.html">(last year's photos)</a>
				<ul class="section2">

					<li>
						<h2>Group Photos</h2>
						<div style="margin: 0 auto; width: 100%; height: 627px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/1jsE-oaWNILcU9845tbw5XjdnpPqO2CLEan9S3KoFIOw/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="627" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Councelors</h2>
						<div style="margin: 0 auto; width: 100%; height: 627px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/1w4QiSyqESeRojXt-S1RNLwxeXdcs4yssyYAiRbEhaUg/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="627" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Staff</h2>
						<div style="margin: 0 auto; width: 100%; height: 627px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/1bsArtqozl8kD5rYhIvl8waf-nb3dc-xaXJGsTl4a3QE/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="627" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Chapel</h2>
						<div style="margin: 0 auto; width: 100%; height: 627px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/1utyG3g07PaqijanDCeHZRHG11fXbwVVCowtKb8c4mRM/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="627" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Bingo</h2>
						<div style="margin: 0 auto; width: 100%; height: 627px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/1qHtXYu0zulRQexDg4d7DZyeoBqzoSdrMbnGwAQlqbnY/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="627" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Olympiada</h2>
						<div style="margin: 0 auto; width: 100%; height: 627px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/15AFhHp009s7lv4-YXu1i6SZT5jHdv_rtSjYkEKTkzls/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="627" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Craft</h2>
						<div style="margin: 0 auto; width: 100%; height: 627px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/1bcu7UgfY-f5a-NRKyA8zATedH01_zfJllZ3R-1D-yJ8/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="627" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Nauka</h2>
						<div style="margin: 0 auto; width: 100%; height: 627px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/1HYfvrJrP9q0jKADqSSo4jM1NTSvd7aXAybmma9Fvchs/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="627" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Outside</h2>
						<div style="margin: 0 auto; width: 100%; height: 627px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/1X_8HE3F8vYujCFwR0WNXfljRbRfT5yhh5qy6tUuW9SE/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="627" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Food</h2>
						<div style="margin: 0 auto; width: 100%; height: 627px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/1ZNmDT6ulAle7Ui_6gHiVBNHwndJOA-HlZidXPRKskw0/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="627" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Trip</h2>
						<div style="margin: 0 auto; width: 100%; height: 627px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/1nRIGp396CTOxJtrjgMKxA00JVDlTxHEaHQjcSx5epbs/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="627" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Spiv</h2>
						<div style="margin: 0 auto; width: 100%; height: 627px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/1B1KdkaCeKSQnl-UoArXqtRFGW12nA9M-GOn7BYBWepo/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="627" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Sport</h2>
						<div style="margin: 0 auto; width: 100%; height: 627px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/1eJgL0Duw1tfnyecNCAeWnKIIhq7RwuNpc8cSSs0H8Ec/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="627" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Skits</h2>
						<div style="margin: 0 auto; width: 100%; height: 627px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/12TDYXyqpOU7lDnJGF1xva-9AzgB4yGXpNxfbtUsbVy0/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="627" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Prayer walk and Vatra</h2>
						<div style="margin: 0 auto; width: 100%; height: 627px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/1Nq4l9NowSHrl9OAwnaR_Hl8ucGtns4g-RM7qPOIKqy8/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="627" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
					<li>
						<h2>Dorms</h2>
						<div style="margin: 0 auto; width: 100%; height: 627px; overflow: hidden;">
							<iframe src="https://docs.google.com/presentation/d/1I3rtpYGf40mm4CeMtIf2Qe-KeqDk1uBHwTMtzbjwxdI/embed?start=true&loop=true&delayms=5000"
									frameborder="0" width="800" height="627" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>						</div>
					</li>
				</ul>
			</div>
