			<div id="content">


				<h1>Our camp is full!</h1>
				<hr>
				<p>
				You may still send in your application, but you will be placed on the waiting list.
				<b>PLEASE DO NOT CALL</b> - we will contact you if a spot becomes available.
				</p>

				<br/>
				<br/>

				<h1>How do I sign up?</h1>

				<hr />

				<p>
				Registration starts Sunday November 13th 2016. Pick up a flyer and registration form <b>in your parish</b>, fill it out and send it along with your check (made out to <code>Break For Jesus</code>) to address provided in the form. If not announced, ask your parish priest for an application form.
				</p>
				<br/>
				<br/>
				<h1>How much?</h1>
				<hr />
				<p>
				Cost is <code>$365</code> per first child, <code>$360</code> per subsequent child from the same family (brother or sister). Cheques must be dated no later than December 31st 2016.
				</p>
				<br/>
				<br/>
				<h1>Note</h1>
				<hr />
				<p>
				Registration is on a first come first serve basis. We must have your registration form and cheque before your spot can be reserved (no faxes please). You will be notified when we receive your application.
				<br/>
				Space is very limited (60 participants), do not delay!
				</p>

				<p>
				<b>We cannot accommodate room allocation requests</b>
				</p>


				<p>
				Need more info? Email us at <a href="mailto:b4j@gmx.com">b4j@gmx.com</a> or call Tanya Choly at <code>905-646-1275</code>
				</p>

			</div>
